disable 2 tests
microsoft/azuredatastudio pull request #12527
Opened 2020-09-21 16:54 UTC by ranasaria

This PR fixes #

2020-09-21 17:03 UTC, ranasaria commented on extensions/azdata/src/test/azdata.test.ts
> +		it.skip('successful update', async function (): Promise<void> {
add a workitem for skipped tests for re-enablment

2020-09-21 17:21 UTC, Charles-Gagnon commented
Are you seeing these tests failing yourself? I'm seeing different ones fail - but I'm on windows which may be why.

2020-09-21 20:26 UTC, Charles-Gagnon requested changes
Do we need this? The tests pass for me on windows and on Linux in the labs, is this an Mac specific issue?

2020-09-22 18:11 UTC, ranasaria commented
No I saw these fail on windows. But if they pass for you then I will abandon skipping them but just investigate to see why they were failing for me on my windows machine.

2020-09-22 18:12 UTC, closed without merging