Update/agent
microsoft/azuredatastudio pull request #13298
Opened 2020-11-07 01:44 UTC by abist

Revert agent fixes and use the same fix in release instead until the refactor is done

also bump agent for insiders

2020-11-08 23:30 UTC, Charles-Gagnon requested changes

2020-11-08 23:30 UTC, Charles-Gagnon commented on src/sql/workbench/contrib/jobManagement/browser/jobsView.component.ts
> +	private filterPlugin: any;
You should be able to leave most of these typings - the filter maps are probably the only ones that will need the full set of fixes. But

2020-11-08 23:30 UTC, Charles-Gagnon commented on src/typings/slickgrid.d.ts
> -			public getFilteredItems(): T[]; // manually adding this type - it's present in the definition but not the typings file from DefinitelyTyped
Definitely keep this IMO - it's not going to affect anything to keep it around and will be useful to have while you work on the full refactor

2020-11-08 23:30 UTC, Charles-Gagnon commented on src/sql/workbench/services/jobManagement/browser/jobManagementUtilities.ts
> +		let temp = icon.className as unknown;
This is broken with this logic - just use what I had since that should be the actual fix anyways.

2020-11-08 23:30 UTC, Charles-Gagnon commented on src/sql/workbench/services/jobManagement/browser/jobManagementUtilities.ts
> +		if (date.includes('1/1/0001')) {
Not sure why you're converting this to an if - that's just adding extra lines of code for the exact same functionality.

2020-11-08 23:30 UTC, Charles-Gagnon commented on src/sql/workbench/contrib/jobManagement/browser/notebooksView.component.ts
> +		let filterPlugin = new HeaderFilter<{ inlineFilters: false }>();
Keep this - what was here is wrong. It should be IItem.

2020-11-08 23:30 UTC, Charles-Gagnon commented on src/sql/workbench/contrib/jobManagement/browser/notebooksView.component.ts
> +		let options = <Slick.GridOptions<any>>{
Just keep this - it should be IItem anyways.

2020-11-08 23:30 UTC, Charles-Gagnon commented on src/sql/workbench/contrib/jobManagement/browser/notebooksView.component.ts
> +	private filterPlugin: any;
You should be able to keep these typed correctly - would prefer not to revert these.

2020-11-08 23:30 UTC, Charles-Gagnon commented on src/sql/workbench/contrib/jobManagement/browser/jobsView.component.ts
> +		let filterPlugin = new HeaderFilter<{ inlineFilters: false }>();
Don't revert this - IItem is the correct type to use here.

2020-11-08 23:30 UTC, Charles-Gagnon commented on src/sql/workbench/contrib/jobManagement/browser/jobsView.component.ts
> +		let options = <Slick.GridOptions<any>>{
Keeping this typed shouldn't change anything.

2020-11-09 01:25 UTC, abist commented
@Charles-Gagnon This PR is to get to the same state as release branch. I'll make the suggested changes in another PR. This is just reverting and applying the commit in release for main

2020-11-09 03:25 UTC, Charles-Gagnon approved these changes
I don't really get the need to match the release branch exactly since these should all be extremely simple changes to make, but if you think that's useful sure.

2020-11-09 17:00 UTC, merged