Disable checkbox for blocking migration issues
microsoft/azuredatastudio pull request #15131
Opened 2021-04-14 17:42 UTC by cssuh

Disable database checkbox if there is a blocking issue (multiple log files, filestream, or db too large)
![disable-checkbox](https://user-images.githubusercontent.com/18150417/114754881-e9592000-9d0d-11eb-8b5c-9f5c35a99c32.PNG)

2021-04-14 17:44 UTC, alanrenmsft commented on extensions/sql-migration/src/models/stateMachine.ts
> +	LOG_FILE = 'Azure SQL Managed Instance does not support multiple log files.',
these strings should be localized and you don't need an enum type for it

2021-04-14 17:49 UTC, alanrenmsft commented on extensions/sql-migration/src/dialog/assessmentResults/sqlDatabasesTree.ts
> +				db.issues.forEach((issue) => {
you should just use the array.find, which will return the first one that matches the criteria, you don't have to go through all the issues.

you can do it inline when you set the enabled property.

2021-04-14 18:47 UTC, aasimkhan30 commented
@cssuh are we sure that this is the best way to match the blocking issues. The rule text might easily change and break this feature. Matching based on rule IDs will be better and will make it easier to add/remove the rules.
What is check ID in assessmentsResultItem and can it be used to uniquely match these rules? Also, in a future PR it will be great if we can document assessment properties in this interface.

https://github.com/microsoft/azuredatastudio/blob/339d908d1d180a91f457aa80e6fa486c8d62a19c/extensions/mssql/src/mssql.d.ts#L523-L524

2021-04-14 19:57 UTC, cssuh commented
@aasimkhan30 @alanrenmsft 
Yes I agree that a ruleID needs to be used, it is actually not passed from the Assessment Results so I am talking with the migration assessments team to have them add it, and will edit the PR once it is available

2021-04-16 22:35 UTC, aasimkhan30 requested changes

2021-04-16 22:35 UTC, aasimkhan30 commented on extensions/sql-migration/src/constants/strings.ts
> +export const BLOCKING_ISSUE_LOG_FILES = localize('sql.migration.blocking.issue.log', "MultipleLogFiles");
I don't think we need to localize these ids. Only the strings that are displayed need to be localized. Just make an array of blocking IDs and check if the id is in that array.

2021-04-16 22:53 UTC, aasimkhan30 approved these changes

2021-04-17 16:03 UTC, merged