Add Notebook telemetry events
microsoft/azuredatastudio pull request #19848
Opened 2022-06-28 13:30 UTC by lucyzhang929

This PR adds telemetry events for: 
- Add Remote Jupyter Book
- Cell Execution Failed (including kernel type and error message)
- Move Cell (including move direction)

2022-06-28 16:03 UTC, Charles-Gagnon requested changes

2022-06-28 16:16 UTC, lucyzhang929 commented on src/sql/workbench/services/notebook/browser/models/cell.ts
> +			this.notebookModel.sendNotebookTelemetryActionEvent(TelemetryKeys.NbTelemetryAction.CellExecutionFailed, { kernel: kernel, errorMessage: message });
Ah I will definitely change that, thanks!

2022-06-30 15:47 UTC, Charles-Gagnon approved these changes

2022-07-01 16:14 UTC, lucyzhang929 commented on src/sql/workbench/services/notebook/browser/models/cell.ts
> +			this.notebookModel.sendNotebookTelemetryActionEvent(TelemetryKeys.NbTelemetryAction.CellExecutionFailed, { kernel: kernel, reason: error.message === 'Canceled' ? 'Canceled' : 'Other' });
Merging what I have for now but will add a helper function when we want to get more specific types.

2022-07-01 16:14 UTC, merged